x-common-settings: &common-settings
  build: .
  restart: always
  volumes:
    - .:/app

services:
  morda_bot:
    <<: *common-settings
    container_name: morda_bot
    env_file:
      - ./envs/morda.env
    ports:
      - "5900:5900" 
