name: Yandex Image Registry Base

on:
    push:
        branches:
            - main

jobs:
  build_base:
    permissions:
        contents: 'read'
        id-token: 'write'

    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set timestamp env variable
          id: timestamp
          run: echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

        - name: Login to ECR
          uses: docker/login-action@v3
          with:
            registry: cr.yandex/crpdt2ulmb7b1hrg6jcd
            username: oauth
            password: ${{ secrets.CLOUD_DOCKER_REGISTRY_KEY }}

        - name: Build and Push the image into Registry
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile.base
            push: true
            tags: cr.yandex/crpdt2ulmb7b1hrg6jcd:${{ steps.timestamp.outputs.timestamp }}